@echo off
echo Instalando dependencias...
pip install supabase python-dotenv
echo Removendo motor (MongoDB)...
pip uninstall motor -y
echo Iniciando servidor...
uvicorn servidor.principal:app --reload