import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';

type Language = 'pt' | 'en' | 'es' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  pt: {
    'dashboard.title': 'Painel de Controle',
    'account.title': 'Gerenciar Conta',
    'sidebar.overview': 'Visão Geral',
    'sidebar.documents': 'Meus Documentos',
    'sidebar.history': 'Histórico',
    'sidebar.sign': 'Assinar Documento',
    'sidebar.send': 'Enviar Envelope',
    'sidebar.account': 'Minha Conta',
    'sidebar.logout': 'Sair',
    'welcome': 'Bem-vindo de volta,',
    'welcome.subtitle': 'Aqui está o resumo das suas atividades recentes.',
    'stats.signed': 'Contratos Assinados',
    'stats.waiting': 'Aguardando Assinatura',
    'stats.total': 'Total de Documentos',
    'activity.title': 'Atividade Recente',
    'table.document': 'Documento',
    'table.recipient': 'Destinatário',
    'table.date': 'Data',
    'table.status': 'Status',
    'status.completed': 'Concluído',
    'status.waiting': 'Aguardando',
    'menu.account': 'Minha Conta',
    'menu.language': 'Idioma',
    'user.plan': 'Plano Gratuito',
    'btn.create_account': 'Criar Conta',
    'btn.login': 'Entrar',
    'nav.features': 'Recursos',
    'nav.pricing': 'Preços',
    'nav.about': 'Sobre',
    // New keys for Meus Documentos
    'documents.title': 'Meus Documentos',
    'documents.new_folder': 'Nova Pasta',
    'documents.upload': 'Novo Documento',
    'documents.search': 'Buscar documentos...',
    'documents.empty': 'Nenhum documento encontrado nesta pasta.',
    'documents.name': 'Nome',
    'documents.date': 'Data',
    'documents.size': 'Tamanho',
    'documents.category': 'Categoria',
    'documents.folder_name': 'Nome da Pasta',
    'documents.create': 'Criar',
    'documents.cancel': 'Cancelar',
    'documents.all': 'Todos os Documentos',
    'documents.uncategorized': 'Sem Categoria',
    'documents.delete': 'Excluir',
    'documents.rename': 'Renomear',
    'documents.move': 'Mover',
    
    // New keys for EnviarDocumento
    'send.title': 'Enviar envelope',
    'send.add_docs': 'Adicionar documentos',
    'send.select_doc': 'Selecione o documento para envio (PDF, DOCX)',
    'send.click_search': 'Clique para buscar em seu computador',
    'send.file_selected': 'Arquivo selecionado:',
    'send.recipients': 'Destinatários',
    'send.self_sign': 'Eu também preciso assinar o documento',
    'send.your_data': 'Seus Dados (Você)',
    'send.your_name': 'Seu Nome',
    'send.your_email': 'Seu E-mail',
    'send.recipient': 'Destinatário',
    'send.name': 'Nome',
    'send.email': 'E-mail',
    'send.role': 'Papel',
    'send.role.signer': 'ASSINANTE',
    'send.role.witness': 'TESTEMUNHA',
    'send.role.approver': 'APROVADOR',
    'send.add_recipient': 'Adicionar outro destinatário',
    'send.message_all': 'Mensagem para todos',
    'send.subject': 'Assunto do E-mail',
    'send.message': 'Mensagem',
    'send.submit': 'Enviar Envelope',
    'send.deadline_title': 'Prazo de Assinatura',
    'send.deadline_label': 'Data Limite para Assinatura',
    'send.auto_reminder': 'Enviar e-mail automático no último dia',
    'send.description': 'Preencha os campos abaixo para configurar o envio do documento para assinatura.',
    
    // New keys for Audit Log
    'log.title': 'Histórico de Ações',
    'log.created': 'Criado',
    'log.sent': 'Enviado',
    'log.viewed': 'Visualizado',
    'log.signed': 'Assinado',
    'log.completed': 'Concluído',
    'log.by': 'Por',   // New keys for Home (Assinar)
    'sign.title': 'Assinador de Contratos Seguro',
    'sign.select_doc': 'Selecione o documento para assinatura (PDF, DOCX)',
    'sign.data_title': 'Dados da Assinatura',
    'sign.contractor': 'Contratante',
    'sign.contracted': 'Contratada',
  

   'sign.type': 'Digitar',
    'sign.draw': 'Desenhar',
    'sign.clear': 'Limpar',
    'sign.full_name': 'Nome completo',
    'sign.submit': 'Assinar Documento',
    // New keys for Dashboard (Account)
    'account.personal_info': 'Informações Pessoais',
    'account.full_name': 'Nome Completo',
    'account.phone': 'Telefone',
    'account.job_title': 'Cargo',
    'account.save': 'Salvar Alterações',
    'account.security': 'Segurança',
    'account.current_password': 'Senha Atual',
    'account.new_password': 'Nova Senha',
    'account.update_password': 'Atualizar Senha',
    'account.plan_subscription': 'Plano e Assinatura',
    'account.plan_status': 'Ativo',
    'account.plan_desc': 'Você tem direito a 5 assinaturas mensais gratuitas.',
    'account.upgrade': 'Fazer Upgrade',
    // New keys for Forms
    'sidebar.forms': 'Formulários',
    'forms.title': 'Gerenciador de Formulários',
    'forms.create': 'Criar Novo Formulário',
    'forms.list': 'Meus Formulários',
    'forms.responses': 'Respostas',
    'forms.send_title': 'Enviar Formulário',
    'forms.field_label': 'Título da Pergunta',
    'forms.field_placeholder': 'Digite sua pergunta...',
    'forms.add_field': 'Adicionar Campo',
    'forms.save': 'Salvar Formulário',
    'forms.send_to': 'Enviar para (E-mail)',
    'forms.subject': 'Assunto',
    'forms.message': 'Mensagem',
    'forms.send_btn': 'Enviar por E-mail',
    'forms.success_send': 'Formulário enviado com sucesso!',
    'forms.no_forms': 'Nenhum formulário criado ainda.',
    'forms.form_title': 'Título do Formulário',
    'forms.form_desc': 'Descrição',
    'forms.create_page_title': 'Criar Formulário',
    'forms.create_title': 'Novo Formulário',
    'forms.create_subtitle': 'Crie perguntas e envie para coleta de dados.',
    'forms.title_placeholder': 'Ex: Pesquisa de Satisfação',
    'forms.recipient_email_label': 'Enviar para (E-mail do destinatário)',
    'forms.recipient_email_placeholder': 'destinatario@exemplo.com',
    'forms.questions_title': 'Perguntas do Formulário',
    'forms.add_question': 'Adicionar Pergunta',
    'forms.no_questions': 'Nenhuma pergunta adicionada.',
    'forms.start_building': 'Clique em "Adicionar Pergunta" para começar a construir seu formulário.',
    'forms.question_number': 'Pergunta',
    'forms.delete': 'Excluir',
    'forms.question_text_label': 'Texto da Pergunta',
    'forms.question_text_placeholder': 'Digite sua pergunta aqui...',
    'forms.response_type_label': 'Tipo de Resposta Esperada',
    'forms.type_short': 'Texto Curto',
    'forms.type_long': 'Texto Longo',
    'forms.type_number': 'Número',
    'forms.type_email': 'E-mail (Validação)',
    'forms.type_date': 'Data',
    'forms.type_select': 'Múltipla Escolha (Seleção)',
    'forms.required': 'Obrigatório',
    'forms.options_title': 'Opções de Resposta',
    'forms.option_placeholder': 'Opção',
    'forms.add_option': 'Adicionar outra opção',
    'forms.submit_btn': 'Enviar Formulário',
    'forms.alert_fill': 'Preencha todos os campos obrigatórios e adicione pelo menos uma pergunta.',
    'forms.alert_success': 'Sucesso! Um link para responder o formulário',
    'forms.alert_sent_to': 'foi enviado para',
    'forms.new_question_default': 'Nova Pergunta',
    'forms.preview_btn': 'Pré-visualizar E-mail',
    'forms.preview_title': 'Pré-visualização do E-mail',
    'forms.email_subject_prefix': 'Formulário: ',
    'forms.email_body_greeting': 'Olá,',
    'forms.email_body_invite': 'Você foi convidado para responder o formulário:',
    'forms.email_cta': 'Responder Formulário',
    'forms.modal_success_title': 'Formulário Enviado com Sucesso!',
    'forms.modal_success_message': 'O convite foi enviado para',
    'forms.modal_close': 'Voltar para o Início',
    // New keys for EnviarComunicado
    'sidebar.announce': 'Enviar Comunicado',
    'announce.title': 'Enviar Comunicado',
    'announce.subtitle': 'Envie e-mails informativos com sua marca.',
    'announce.logo_label': 'Logo do Cabeçalho',
    'announce.logo_placeholder': 'Clique para fazer upload da logo',
    'announce.subject_label': 'Assunto do E-mail',
    'announce.message_label': 'Corpo da Mensagem',
    'announce.recipients_label': 'Destinatários (separados por vírgula)',
    'announce.recipients_placeholder': 'exemplo@email.com, outro@email.com',
    'announce.preview_btn': 'Pré-visualizar',
    'announce.send_btn': 'Enviar Comunicado',
    'announce.preview_title': 'Pré-visualização do E-mail',
    'announce.confirm_send': 'Confirmar Envio',
    'announce.edit': 'Voltar e Editar',
    'announce.success': 'Comunicado enviado com sucesso!',
    'announce.logo_help': 'Recomendado: Imagem PNG ou JPG transparente.',
    // New keys for History
    'history.title': 'Histórico de Comunicados',
    'history.subtitle': 'Acompanhe o desempenho dos comunicados enviados e a taxa de abertura.',
    'history.subject': 'Assunto',
    'history.sent_at': 'Enviado em',
    'history.recipients': 'Destinatários',
    'history.opens': 'Aberturas',
    'history.open_rate': 'Taxa de Abertura',
    'history.status_opened': 'Abriu',
    'history.status_not_opened': 'Não abriu',
    'history.rate': 'Taxa',
    'history.actions': 'Ações',
    'history.view_recipients': 'Ver destinatários',
    'history.no_announcements': 'Nenhum comunicado enviado ainda.',
    'history.recipients_opens_title': 'Destinatários e Aberturas',
    'history.recipients_opens_subtitle': 'Veja quem recebeu e quem abriu o comunicado selecionado.',
    'history.select_instruction': 'Selecione um comunicado na lista para ver os detalhes.',
    'history.name': 'Nome',
    'history.email': 'E-mail',
    'history.status': 'Status',
    'history.first_open': 'Primeira abertura',
    'history.no_recipients': 'Nenhum destinatário encontrado para este comunicado.',
    'history.status_opened_badge': 'Aberto',
    'history.status_not_opened_badge': 'Não aberto',
    // New keys for Password Recovery
    'recover.title': 'Recuperar Senha',
    'recover.subtitle': 'Digite seu e-mail para receber as instruções de recuperação.',
    'recover.email_label': 'Seu E-mail',
    'recover.email_placeholder': 'Digite seu e-mail cadastrado',
    'recover.submit_btn': 'Enviar Instruções',
    'recover.back_login': 'Voltar para o Login',
    'recover.success_message': 'Se o e-mail estiver cadastrado, você receberá as instruções em breve.',
    'recover.forgot_password_text': 'Esqueceu a senha?',
    'recover.click_here': 'Clique aqui!',
    // New keys for Modelos de Contrato
    'sidebar.templates': 'Modelos de Contrato',
    'templates.title': 'Biblioteca de Modelos',
    'templates.subtitle': 'Selecione um modelo, preencha os dados e baixe seu contrato pronto.',
    'templates.use_btn': 'Usar Modelo',
    'templates.download_word': 'Baixar em Word',
    'templates.download_pdf': 'Baixar em PDF',
    'templates.fill_details': 'Preencher Dados',
    'templates.preview': 'Pré-visualização',
    'templates.back': 'Voltar para Lista',
    'templates.fill_title': 'Preencha os dados do contrato',
    'templates.generate_btn': 'Gerar Contrato',
    'templates.send_sign': 'Enviar para Assinatura',
    // New keys for Landing Page
    'landing.nav.home': 'Início',
    'landing.nav.menu': 'Menu',
    'landing.nav.features': 'Recursos',
    'landing.nav.pricing': 'Preços',
    'landing.nav.about': 'Sobre',
    'landing.nav.contact': 'Contato',
    'landing.nav.login': 'Entrar',
    'landing.nav.platform': 'Acessar Plataforma',
    'landing.hero.title_start': 'Assine contratos',
    'landing.hero.title_end': 'em segundos',
    'landing.hero.subtitle': 'A plataforma mais moderna para assinatura digital. Rápido, seguro e com validade jurídica garantida.',
    'landing.hero.start': 'Começar Gratuitamente',
    'landing.hero.demo': 'Ver Demonstração',
    'landing.features.title_start': 'Por que escolher o',
    'landing.features.subtitle': 'Uma plataforma completa para gerenciar seus documentos, assinaturas e comunicados em um só lugar.',
    'landing.card.contract.title': 'Assinatura de Contratos',
    'landing.card.contract.desc': 'Envie contratos para assinatura com validade jurídica garantida. Processo simples, seguro e 100% digital.',
    'landing.card.multi.title': 'Múltiplos Destinatários',
    'landing.card.multi.desc': 'Precisa de várias assinaturas? Envie para diversos destinatários por e-mail simultaneamente.',
    'landing.card.forms.title': 'Formulários Integrados',
    'landing.card.forms.desc': 'Crie formulários personalizados e envie diretamente por e-mail para coleta de dados estruturados.',
    'landing.card.announce.title': 'Envio de Comunicados',
    'landing.card.announce.desc': 'Mantenha todos informados. Envie comunicados e avisos importantes por e-mail de forma rápida.',
    'landing.card.simple.title': 'Sem Complicação',
    'landing.card.simple.desc': 'Feito para facilitar seu trabalho. Interface intuitiva e acessível para você focar no que importa.',
    'landing.card.secure.title': 'Totalmente Seguro',
    'landing.card.secure.desc': 'Seus dados protegidos com criptografia de ponta a ponta. Segurança e conformidade em primeiro lugar.',
    'landing.about.title': 'Sobre a',
    'landing.about.desc1': 'A VERYSING nasceu com o propósito de simplificar e proteger as relações comerciais no ambiente digital. Nossa plataforma une a robustez da segurança criptográfica com uma experiência de uso intuitiva e fluida.',
    'landing.about.desc2': 'Transforme a burocracia em agilidade. Assine contratos em segundos, de qualquer lugar do mundo.',
    'landing.about.stat1': 'Seguro',
    'landing.about.stat2': 'Disponível',
    'landing.about.badge': 'Assinado Digitalmente',
    'landing.demo.title': 'Veja a',
    'landing.demo.title_end': 'em ação',
    'landing.demo.desc': 'Descubra como nossa plataforma pode transformar sua gestão de documentos e gerar mais lucro para seu negócio.',
    'landing.demo.soon': 'Vídeo de Demonstração em Breve',
    'landing.pricing.title': 'Planos Flexíveis',
    'landing.pricing.subtitle': 'Escolha o plano ideal para sua necessidade',
    'landing.pricing.free.title': 'Gratuito',
    'landing.pricing.free.btn': 'Começar Grátis',
    'landing.pricing.free.feat1': '5 contratos/mês',
    'landing.pricing.free.feat2': '10 docs no drive',
    'landing.pricing.free.feat3': '1 formulário ativo / 100 respostas/mês',
    'landing.pricing.free.feat4': 'TLS',
    'landing.pricing.pro.title': 'Profissional',
    'landing.pricing.pro.popular': 'MAIS POPULAR',
    'landing.pricing.pro.btn': 'Assinar Pro',
    'landing.pricing.pro.feat1': '15 contratos/mês',
    'landing.pricing.pro.feat2': '30 docs no drive',
    'landing.pricing.pro.feat3': 'Formulários ilimitados / 1.000 respostas/mês',
    'landing.pricing.pro.feat4': '10 comunicados/mês (até 2.000 e‑mails/mês)',
    'landing.pricing.pro.feat5': 'TLS',
    'landing.pricing.ent.title': 'Empresarial',
    'landing.pricing.ent.btn': 'Assinar Empresarial',
    'landing.pricing.ent.feat1': 'Ilimitados contratos/mês',
    'landing.pricing.ent.feat2': '200 docs no drive',
    'landing.pricing.ent.feat3': 'Formulários ilimitados / 10.000 respostas/mês',
    'landing.pricing.ent.feat4': '50 comunicados/mês (até 25.000 e‑mails/mês)',
    'landing.pricing.ent.feat5': 'TLS',
    'landing.footer': '© 2026 VERYSING. Todos os direitos reseazrvados.',
    // Contact Page
    'contact.title': 'Fale Conosco',
    'contact.subtitle': 'Preencha o formulário abaixo e entraremos em contato o mais breve possível.',
    'contact.form.title': 'Envie uma mensagem',
    'contact.form.name': 'Nome',
    'contact.form.name_placeholder': 'Seu nome completo',
    'contact.form.email': 'Email',
    'contact.form.email_placeholder': 'seu@email.com',
    'contact.form.subject': 'Assunto',
    'contact.form.subject_placeholder': 'Como podemos ajudar?',
    'contact.form.message': 'Mensagem',
    'contact.form.message_placeholder': 'Descreva sua dúvida ou solicitação...',
    'contact.form.submit': 'Enviar Mensagem',
    'contact.info.title_start': 'Simplificando',
    'contact.info.title_middle': 'documentos',
    'contact.info.title_connector': ', conectando',
    'contact.info.title_end': 'pessoas',
    'contact.info.desc': 'A Verysing nasceu para desburocratizar assinaturas. Mais do que uma plataforma, somos seus parceiros na agilidade dos negócios, garantindo segurança e validade jurídica em cada acordo.',
    'contact.info.response_title': 'Como receberei a resposta?',
    'contact.info.response_desc1': 'Nossa equipe de suporte analisará sua mensagem e enviará a resposta diretamente para o email informado no formulário.',
    'contact.info.response_desc2': 'Por favor, verifique também sua caixa de spam ou lixo eletrônico para garantir que não perdeu nosso retorno.',
    'contact.alert.success': 'Sua mensagem foi enviada para contato.verysing@gmail.com! (Simulação)',
    // Payment Page
    'payment.title': 'Pagamento',
    'payment.subtitle': 'Pagamento do plano',
    'payment.info_title': 'Informações de pagamento',
    'payment.info_desc': 'Preencha os dados abaixo para finalizar a assinatura do seu plano VerySing.',
    'payment.secure': 'Pagamento protegido com criptografia TLS',
    'payment.account': 'Conta:',
    'payment.select_plan': 'Selecione o plano desejado',
    'payment.plan_free': 'Plano Gratuito',
    'payment.plan_pro': 'Plano Profissional',
    'payment.plan_ent': 'Plano Empresarial',
    'payment.desc_free': 'Acesso básico: 5 docs/mês, Drive e 1 Formulário.',
    'payment.desc_pro': 'Ilimitado: Assinaturas, Drive, Forms e Comunicados.',
    'payment.desc_ent': 'Para empresas: Gestão de equipe e envios em massa.',
    'payment.billing_annual_discount': 'Faturamento anual com 10% de desconto.',
    'payment.free_plan_info': 'O Plano Gratuito oferece acesso básico à plataforma sem custos mensais.',
    'payment.free_plan_confirm_info': 'Ao confirmar, seu plano será alterado imediatamente.',
    'payment.confirm_free': 'Confirmar Plano Gratuito',
    'payment.method_label': 'Forma de pagamento',
    'payment.method_card': 'Cartão de Crédito',
    'payment.method_boleto': 'Boleto Bancário',
    'payment.method_pix': 'Pix',
    'payment.billing_cycle': 'Ciclo de faturamento',
    'payment.billing_monthly': 'Mensal',
    'payment.billing_annual': 'Anual (Economize 10%)',
    'payment.card_number': 'Número do cartão',
    'payment.card_name': 'Nome no cartão',
    'payment.card_expiry': 'Validade (MM/AA)',
    'payment.card_cvv': 'Código de segurança (CVV)',
    'payment.pay_now': 'Pagar Agora',
    'payment.processing': 'Processando...',
    'payment.generate_boleto': 'Gerar Boleto',
    'payment.generate_pix': 'Gerar Pix',
    'payment.boleto_title': 'Pagamento via Boleto Bancário',
    'payment.boleto_desc': 'O boleto será gerado na próxima tela. O prazo de compensação é de até 3 dias úteis.',
    'payment.pix_title': 'Pagamento via Pix',
    'payment.pix_desc': 'O código Pix será gerado na próxima tela. A aprovação é imediata.',
    'payment.alert_fill': 'Preencha todos os dados do cartão para continuar.',
    'payment.success': 'Pagamento realizado com sucesso!',
  },
  en: {
    'dashboard.title': 'Dashboard',
    'account.title': 'Manage Account',
    'sidebar.overview': 'Overview',
    'sidebar.documents': 'My Documents',
    'sidebar.history': 'History',
    'sidebar.sign': 'Sign Document',
    'sidebar.send': 'Send Envelope',
    'sidebar.account': 'My Account',
    'sidebar.logout': 'Logout',
    'welcome': 'Welcome back,',
    'welcome.subtitle': 'Here is your recent activity summary.',
    'stats.signed': 'Signed Contracts',
    'stats.waiting': 'Waiting Signature',
    'stats.total': 'Total Documents',
    'activity.title': 'Recent Activity',
    'table.document': 'Document',
    'table.recipient': 'Recipient',
    'table.date': 'Date',
    'table.status': 'Status',
    'status.completed': 'Completed',
    'status.waiting': 'Waiting',
    'menu.account': 'My Account',
    'menu.language': 'Language',
    'user.plan': 'Free Plan',
    'btn.create_account': 'Sign Up',
    'btn.login': 'Login',
    'landing.nav.home': 'Home',
    'landing.nav.menu': 'Menu',
    'landing.nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    // New keys for EnviarDocumento
    'documents.title': 'My Documents',
    'documents.new_folder': 'New Folder',
    'documents.upload': 'New Document',
    'documents.search': 'Search documents...',
    'documents.empty': 'No documents found in this folder.',
    'documents.name': 'Name',
    'documents.date': 'Date',
    'documents.size': 'Size',
    'documents.category': 'Category',
    'documents.folder_name': 'Folder Name',
    'documents.create': 'Create',
    'documents.cancel': 'Cancel',
    'documents.all': 'All Documents',
    'documents.uncategorized': 'Uncategorized',
    'documents.delete': 'Delete',
    'documents.rename': 'Rename',
    'documents.move': 'Move',

    // New keys for History
    'history.title': 'Communication History',
    'history.subtitle': 'Track the performance of sent announcements and open rates.',
    'history.subject': 'Subject',
    'history.sent_at': 'Sent At',
    'history.recipients': 'Recipients',
    'history.opens': 'Opens',
    'history.open_rate': 'Open Rate',
    'history.status_opened': 'Opened',
    'history.status_not_opened': 'Not Opened',
    'history.rate': 'Rate',
    'history.actions': 'Actions',
    'history.view_recipients': 'View recipients',
    'history.no_announcements': 'No announcements sent yet.',
    'history.recipients_opens_title': 'Recipients and Opens',
    'history.recipients_opens_subtitle': 'See who received and opened the selected announcement.',
    'history.select_instruction': 'Select an announcement from the list to see details.',
    'history.name': 'Name',
    'history.email': 'Email',
    'history.status': 'Status',
    'history.first_open': 'First open',
    'history.no_recipients': 'No recipients found for this announcement.',
    'history.status_opened_badge': 'Opened',
    'history.status_not_opened_badge': 'Not opened',

    'send.title': 'Send Envelope',
    'send.add_docs': 'Add Documents',
    'send.select_doc': 'Select document to send (PDF, DOCX)',
    'send.click_search': 'Click to browse your computer',
    'send.file_selected': 'File selected:',
    'send.recipients': 'Recipients',
    'send.self_sign': 'I also need to sign the document',
    'send.your_data': 'Your Details (You)',
    'send.your_name': 'Your Name',
    'send.your_email': 'Your Email',
    'send.recipient': 'Recipient',
    'send.name': 'Name',
    'send.email': 'Email',
    'send.role': 'Role',
    'send.role.signer': 'SIGNER',
    'send.role.witness': 'WITNESS',
    'send.role.approver': 'APPROVER',
    'send.add_recipient': 'Add another recipient',
    'send.message_all': 'Message to all',
    'send.subject': 'Email Subject',
    'send.message': 'Message',
    'send.submit': 'Send Envelope',
    'send.deadline_title': 'Signature Deadline',
    'send.deadline_label': 'Deadline Date for Signature',
    'send.auto_reminder': 'Send automatic email on the last day',
    'send.description': 'Fill in the fields below to configure the document for signature.',

    // New keys for Audit Log
    'log.title': 'Action Log',
    'log.created': 'Created',
    'log.sent': 'Sent',
    'log.viewed': 'Viewed',
    'log.signed': 'Signed',
    'log.completed': 'Completed',
    'log.by': 'By',

    // New keys for Home (Assinar)
    'sign.title': 'Secure Contract Signer',
    'sign.select_doc': 'Select document for signature (PDF, DOCX)',
    'sign.data_title': 'Signature Data',
    'sign.contractor': 'Contractor',
    'sign.contracted': 'Contracted',
    'sign.type': 'Type',
    'sign.draw': 'Draw',
    // New keys for EnviarComunicado
    'sidebar.announce': 'Send Announcement',
    'announce.title': 'Send Announcement',
    'announce.subtitle': 'Send informative emails with your brand.',
    'announce.logo_label': 'Header Logo',
    'announce.logo_placeholder': 'Click to upload logo',
    'announce.subject_label': 'Email Subject',
    'announce.message_label': 'Message Body',
    'announce.recipients_label': 'Recipients (comma separated)',
    'announce.recipients_placeholder': 'example@email.com, other@email.com',
    'announce.preview_btn': 'Preview',
    'announce.send_btn': 'Send Announcement',
    'announce.preview_title': 'Email Preview',
    'announce.confirm_send': 'Confirm Send',
    'announce.edit': 'Back to Edit',
    'announce.success': 'Announcement sent successfully!',
    'announce.logo_help': 'Recommended: Transparent PNG or JPG image.',
    // New keys for Password Recovery
    'recover.title': 'Recover Password',
    'recover.subtitle': 'Enter your email to receive recovery instructions.',
    'recover.email_label': 'Your Email',
    'recover.email_placeholder': 'Enter your registered email',
    'recover.submit_btn': 'Send Instructions',
    'recover.back_login': 'Back to Login',
    'recover.success_message': 'If the email is registered, you will receive instructions shortly.',
    'recover.forgot_password_text': 'Forgot password?',
    // Payment Page
    'payment.title': 'Payment',
    'payment.subtitle': 'Plan Payment',
    'payment.info_title': 'Payment Information',
    'payment.info_desc': 'Fill in the details below to complete your VerySing plan subscription.',
    'payment.secure': 'Payment protected with TLS encryption',
    'payment.account': 'Account:',
    'payment.select_plan': 'Select desired plan',
    'payment.plan_free': 'Free Plan',
    'payment.plan_pro': 'Professional Plan',
    'payment.plan_ent': 'Enterprise Plan',
    'payment.desc_free': 'Free plan already activated, no payment required.',
    'payment.desc_pro': 'Ideal for professionals and small businesses with frequent use.',
    'payment.desc_ent': 'For teams and companies needing advanced features.',
    'payment.billing_annual_discount': 'Annual billing with 10% discount.',
    'payment.free_plan_info': 'The Free Plan offers basic access to the platform with no monthly costs.',
    'payment.free_plan_confirm_info': 'Upon confirmation, your plan will be changed immediately.',
    'payment.confirm_free': 'Confirm Free Plan',
    'payment.method_label': 'Payment Method',
    'payment.method_card': 'Credit Card',
    'payment.method_boleto': 'Bank Slip (Boleto)',
    'payment.method_pix': 'Pix',
    'payment.billing_cycle': 'Billing Cycle',
    'payment.billing_monthly': 'Monthly',
    'payment.billing_annual': 'Annual (Save 10%)',
    'payment.card_number': 'Card Number',
    'payment.card_name': 'Name on Card',
    'payment.card_expiry': 'Expiry (MM/YY)',
    'payment.card_cvv': 'Security Code (CVV)',
    'payment.pay_now': 'Pay Now',
    'payment.processing': 'Processing...',
    'payment.generate_boleto': 'Generate Bank Slip',
    'payment.generate_pix': 'Generate Pix',
    'payment.boleto_title': 'Payment via Bank Slip',
    'payment.boleto_desc': 'The bank slip will be generated on the next screen. Clearance time is up to 3 business days.',
    'payment.pix_title': 'Payment via Pix',
    'payment.pix_desc': 'The Pix code will be generated on the next screen. Approval is immediate.',
    'payment.alert_fill': 'Fill in all card details to continue.',
    'payment.success': 'Payment successful!',
    'recover.click_here': 'Click here!',
    // New keys for Modelos de Contrato
    'sidebar.templates': 'Contract Templates',
    'templates.title': 'Template Library',
    'templates.subtitle': 'Select a template, fill in the details and download your ready-to-use contract.',
    'templates.use_btn': 'Use Template',
    'templates.download_word': 'Download Word',
    'templates.download_pdf': 'Download PDF',
    'templates.fill_details': 'Fill Details',
    'templates.preview': 'Preview',
    'templates.back': 'Back to List',
    'templates.fill_title': 'Fill in contract details',
    'templates.generate_btn': 'Generate Contract',
    'templates.send_sign': 'Send for Signature',
    // New keys for Landing Page
    'landing.nav.pricing': 'Pricing',
    'landing.nav.about': 'About',
    'landing.nav.contact': 'Contact',
    'landing.nav.login': 'Login',
    'landing.nav.platform': 'Access Platform',
    'landing.hero.title_start': 'Sign contracts',
    'landing.hero.title_end': 'in seconds',
    'landing.hero.subtitle': 'The most modern platform for digital signatures. Fast, secure, and legally binding.',
    'landing.hero.start': 'Start for Free',
    'landing.hero.demo': 'View Demo',
    'landing.features.title_start': 'Why choose',
    'landing.features.subtitle': 'A complete platform to manage your documents, signatures, and announcements in one place.',
    'landing.card.contract.title': 'Contract Signing',
    'landing.card.contract.desc': 'Send contracts for signature with legal validity. Simple, secure, and 100% digital process.',
    'landing.card.multi.title': 'Multiple Recipients',
    'landing.card.multi.desc': 'Need multiple signatures? Send to multiple recipients via email simultaneously.',
    'landing.card.forms.title': 'Integrated Forms',
    'landing.card.forms.desc': 'Create custom forms and send directly via email for structured data collection.',
    'landing.card.announce.title': 'Send Announcements',
    'landing.card.announce.desc': 'Keep everyone informed. Send important announcements and notices via email quickly.',
    'landing.card.simple.title': 'No Complications',
    'landing.card.simple.desc': 'Made to make your work easier. Intuitive and accessible interface so you can focus on what matters.',
    'landing.card.secure.title': 'Totally Secure',
    'landing.card.secure.desc': 'Your data protected with end-to-end encryption. Security and compliance first.',
    'landing.about.title': 'About',
    'landing.about.desc1': 'VERYSING was born with the purpose of simplifying and protecting commercial relationships in the digital environment. Our platform combines robust cryptographic security with an intuitive and fluid user experience.',
    'landing.about.desc2': 'Transform bureaucracy into agility. Sign contracts in seconds, from anywhere in the world.',
    'landing.about.stat1': 'Secure',
    'landing.about.stat2': 'Available',
    'landing.about.badge': 'Digitally Signed',
    'landing.demo.title': 'See',
    'landing.demo.title_end': 'in action',
    'landing.demo.desc': 'Discover how our platform can transform your document management and generate more profit for your business.',
    'landing.demo.soon': 'Demo Video Coming Soon',
    'landing.pricing.title': 'Flexible Plans',
    'landing.pricing.subtitle': 'Choose the ideal plan for your needs',
    'landing.pricing.free.title': 'Free',
    'landing.pricing.free.btn': 'Start for Free',
    'landing.pricing.free.feat1': '5 contracts/month',
    'landing.pricing.free.feat2': '10 drive docs',
    'landing.pricing.free.feat3': '1 active form / 100 responses/month',
    'landing.pricing.free.feat4': 'TLS',
    'landing.pricing.pro.title': 'Professional',
    'landing.pricing.pro.popular': 'MOST POPULAR',
    'landing.pricing.pro.btn': 'Subscribe Pro',
    'landing.pricing.pro.feat1': '15 contracts/month',
    'landing.pricing.pro.feat2': '30 drive docs',
    'landing.pricing.pro.feat3': 'Unlimited forms / 1,000 responses/month',
    'landing.pricing.pro.feat4': '10 announcements/month (up to 2,000 emails)',
    'landing.pricing.pro.feat5': 'TLS',
    'landing.pricing.ent.title': 'Enterprise',
    'landing.pricing.ent.btn': 'Subscribe Enterprise',
    'landing.pricing.ent.feat1': 'Unlimited contracts/month',
    'landing.pricing.ent.feat2': '200 drive docs',
    'landing.pricing.ent.feat3': 'Unlimited forms / 10,000 responses/month',
    'landing.pricing.ent.feat4': '50 announcements/month (up to 25,000 emails)',
    'landing.pricing.ent.feat5': 'TLS',
    'landing.footer': '© 2026 VERYSING. All rights reserved.',
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Fill out the form below and we will contact you as soon as possible.',
    'contact.form.title': 'Send a message',
    'contact.form.name': 'Name',
    'contact.form.name_placeholder': 'Your full name',
    'contact.form.email': 'Email',
    'contact.form.email_placeholder': 'your@email.com',
    'contact.form.subject': 'Subject',
    'contact.form.subject_placeholder': 'How can we help?',
    'contact.form.message': 'Message',
    'contact.form.message_placeholder': 'Describe your question or request...',
    'contact.form.submit': 'Send Message',
    'contact.info.title_start': 'Simplifying',
    'contact.info.title_middle': 'documents',
    'contact.info.title_connector': ', connecting',
    'contact.info.title_end': 'people',
    'contact.info.desc': 'Verysing was born to cut red tape in signatures. More than a platform, we are your partners in business agility, ensuring security and legal validity in every agreement.',
    'contact.info.response_title': 'How will I receive the answer?',
    'contact.info.response_desc1': 'Our support team will analyze your message and send the reply directly to the email provided in the form.',
    'contact.info.response_desc2': 'Please also check your spam or junk folder to ensure you didn\'t miss our return.',
    'contact.alert.success': 'Your message has been sent to contact.verysing@gmail.com! (Simulation)',
    
    // Additional keys
    'account.personal_info': 'Personal Information',
    'account.full_name': 'Full Name',
    'account.phone': 'Phone',
    'account.job_title': 'Job Title',
    'account.save': 'Save Changes',
    'account.security': 'Security',
    'account.current_password': 'Current Password',
    'account.new_password': 'New Password',
    'account.update_password': 'Update Password',
    'account.plan_subscription': 'Plan & Subscription',
    'account.plan_status': 'Active',
    'account.plan_desc': 'You have 5 free monthly signatures.',
    'account.upgrade': 'Upgrade Plan',
    // New keys for Forms
    'sidebar.forms': 'Forms',
    'forms.title': 'Form Manager',
    'forms.create': 'Create New Form',
    'forms.list': 'My Forms',
    'forms.responses': 'Responses',
    'forms.send_title': 'Send Form',
    'forms.field_label': 'Question Title',
    'forms.field_placeholder': 'Type your question...',
    'forms.add_field': 'Add Field',
    'forms.save': 'Save Form',
    'forms.send_to': 'Send to (Email)',
    'forms.subject': 'Subject',
    'forms.message': 'Message',
    'forms.send_btn': 'Send via Email',
    'forms.success_send': 'Form sent successfully!',
    'forms.no_forms': 'No forms created yet.',
    'forms.form_title': 'Form Title',
    'forms.form_desc': 'Description',
    'forms.create_page_title': 'Create Form',
    'forms.create_title': 'New Form',
    'forms.create_subtitle': 'Create questions and send for data collection.',
    'forms.title_placeholder': 'Ex: Satisfaction Survey',
    'forms.recipient_email_label': 'Send to (Recipient Email)',
    'forms.recipient_email_placeholder': 'recipient@example.com',
    'forms.questions_title': 'Form Questions',
    'forms.add_question': 'Add Question',
    'forms.no_questions': 'No questions added.',
    'forms.start_building': 'Click "Add Question" to start building your form.',
    'forms.question_number': 'Question',
    'forms.delete': 'Delete',
    'forms.question_text_label': 'Question Text',
    'forms.question_text_placeholder': 'Type your question here...',
    'forms.response_type_label': 'Expected Response Type',
    'forms.type_short': 'Short Text',
    'forms.type_long': 'Long Text',
    'forms.type_number': 'Number',
    'forms.type_email': 'Email (Validation)',
    'forms.type_date': 'Date',
    'forms.type_select': 'Multiple Choice (Selection)',
    'forms.required': 'Required',
    'forms.options_title': 'Response Options',
    'forms.option_placeholder': 'Option',
    'forms.add_option': 'Add another option',
    'forms.submit_btn': 'Send Form',
    'forms.alert_fill': 'Please fill in all required fields and add at least one question.',
    'forms.alert_success': 'Success! A link to answer the form',
    'forms.alert_sent_to': 'was sent to',
    'forms.new_question_default': 'New Question',
    'forms.preview_btn': 'Preview Email',
    'forms.preview_title': 'Email Preview',
    'forms.email_subject_prefix': 'Form: ',
    'forms.email_body_greeting': 'Hello,',
    'forms.email_body_invite': 'You have been invited to answer the form:',
    'forms.email_cta': 'Answer Form',
    'forms.modal_success_title': 'Form Sent Successfully!',
    'forms.modal_success_message': 'The invitation has been sent to',
    'forms.modal_close': 'Back to Dashboard'
  },
  es: {
    'dashboard.title': 'Panel de Control',
    'account.title': 'Gestionar Cuenta',
    'sidebar.overview': 'Visión General',
    'sidebar.documents': 'Mis Documentos',
    'sidebar.history': 'Historial',
    'sidebar.sign': 'Firmar Documento',
    'sidebar.send': 'Enviar Sobre',
    'sidebar.account': 'Mi Cuenta',
    'sidebar.logout': 'Cerrar Sesión',
    'welcome': 'Bienvenido de nuevo,',
    'welcome.subtitle': 'Aquí está el resumen de sus actividades recientes.',
    'stats.signed': 'Contratos Firmados',
    'stats.waiting': 'Esperando Firma',
    'stats.total': 'Total de Documentos',
    'activity.title': 'Actividad Reciente',
    'table.document': 'Documento',
    'table.recipient': 'Destinatario',
    'table.date': 'Fecha',
    'table.status': 'Estado',
    'status.completed': 'Completado',
    'status.waiting': 'Esperando',
    'menu.account': 'Mi Cuenta',
    'menu.language': 'Idioma',
    'user.plan': 'Plan Gratuito',
    'btn.create_account': 'Registrarse',
    'btn.login': 'Entrar',
    'landing.nav.home': 'Inicio',
    'landing.nav.menu': 'Menú',
    'landing.nav.features': 'Características',
    'nav.pricing': 'Precios',
    'nav.about': 'Sobre',
    // New keys for EnviarDocumento
    'documents.title': 'Mis Documentos',
    'documents.new_folder': 'Nueva Carpeta',
    'documents.upload': 'Nuevo Documento',
    'documents.search': 'Buscar documentos...',
    'documents.empty': 'No se encontraron documentos en esta carpeta.',
    'documents.name': 'Nombre',
    'documents.date': 'Fecha',
    'documents.size': 'Tamaño',
    'documents.category': 'Categoría',
    'documents.folder_name': 'Nombre de la Carpeta',
    'documents.create': 'Crear',
    'documents.cancel': 'Cancelar',
    'documents.all': 'Todos los Documentos',
    'documents.uncategorized': 'Sin Categoría',
    'documents.delete': 'Eliminar',
    'documents.rename': 'Renombrar',
    'documents.move': 'Mover',

    'send.title': 'Enviar Sobre',
    'send.add_docs': 'Añadir Documentos',
    'send.select_doc': 'Seleccione el documento para enviar (PDF, DOCX)',
    'send.click_search': 'Haga clic para buscar en su computadora',
    'send.file_selected': 'Archivo seleccionado:',
    'send.recipients': 'Destinatarios',
    'send.self_sign': 'Yo también necesito firmar el documento',
    'send.your_data': 'Sus Datos (Usted)',
    'send.your_name': 'Su Nombre',
    'send.your_email': 'Su Correo',
    'send.recipient': 'Destinatario',
    'send.name': 'Nombre',
    'send.email': 'Correo',
    'send.role': 'Rol',
    'send.role.signer': 'FIRMANT',
    'send.role.witness': 'TESTIGO',
    'send.role.approver': 'APROBADOR',
    'send.add_recipient': 'Añadir otro destinatario',
    'send.message_all': 'Mensaje para todos',
    'send.subject': 'Asunto del Correo',
    'send.message': 'Mensaje',
    'send.submit': 'Enviar Sobre',
    'send.deadline_title': 'Plazo de Firma',
    'send.deadline_label': 'Fecha Límite para Firma',
    'send.auto_reminder': 'Enviar correo automático el último día',
    'send.description': 'Rellene los campos a continuación para configurar el envío del documento.',
    // New keys for Home (Assinar)
    'sign.title': 'Firmante de Contratos Seguro',
    'sign.select_doc': 'Seleccione documento para firma (PDF, DOCX)',
    'sign.data_title': 'Datos de la Firma',
    'sign.contractor': 'Contratante',
    'sign.contracted': 'Contratado',
    'sign.type': 'Escribir',
    'sign.draw': 'Dibujar',
    // New keys for EnviarComunicado
    'sidebar.announce': 'Enviar Comunicado',
    'announce.title': 'Enviar Comunicado',
    'announce.subtitle': 'Envía correos informativos con tu marca.',
    'announce.logo_label': 'Logo del Encabezado',
    'announce.logo_placeholder': 'Clic para subir logo',
    'announce.subject_label': 'Asunto del Correo',
    'announce.message_label': 'Cuerpo del Mensaje',
    'announce.recipients_label': 'Destinatarios (separados por coma)',
    'announce.recipients_placeholder': 'ejemplo@email.com, otro@email.com',
    'announce.preview_btn': 'Previsualizar',
    'announce.send_btn': 'Enviar Comunicado',
    'announce.preview_title': 'Previsualización del Correo',
    'announce.confirm_send': 'Confirmar Envío',
    'announce.edit': 'Volver y Editar',
    'announce.success': '¡Comunicado enviado con éxito!',
    'announce.logo_help': 'Recomendado: Imagen PNG o JPG transparente.',
    // New keys for History
    'history.title': 'Historial de Comunicados',
    'history.subtitle': 'Seguimiento del rendimiento de los anuncios enviados y las tasas de apertura.',
    'history.subject': 'Asunto',
    'history.sent_at': 'Enviado en',
    'history.recipients': 'Destinatarios',
    'history.opens': 'Aperturas',
    'history.open_rate': 'Tasa de Apertura',
    'history.status_opened': 'Abrió',
    'history.status_not_opened': 'No abrió',
    'history.rate': 'Tasa',
    'history.actions': 'Acciones',
    'history.view_recipients': 'Ver destinatarios',
    'history.no_announcements': 'No se han enviado comunicados aún.',
    'history.recipients_opens_title': 'Destinatarios y Aperturas',
    'history.recipients_opens_subtitle': 'Vea quién recibió y abrió el comunicado seleccionado.',
    'history.select_instruction': 'Seleccione un comunicado de la lista para ver detalles.',
    'history.name': 'Nombre',
    'history.email': 'Correo',
    'history.status': 'Estado',
    'history.first_open': 'Primera apertura',
    'history.no_recipients': 'No se encontraron destinatarios para este comunicado.',
    'history.status_opened_badge': 'Abierto',
    'history.status_not_opened_badge': 'No abierto',
    // New keys for Password Recovery
    'recover.title': 'Recuperar Contraseña',
    'recover.subtitle': 'Ingrese su correo electrónico para recibir instrucciones de recuperación.',
    'recover.email_label': 'Su Correo Electrónico',
    'recover.email_placeholder': 'Ingrese su correo registrado',
    'recover.submit_btn': 'Enviar Instrucciones',
    'recover.back_login': 'Volver al Inicio de Sesión',
    'recover.success_message': 'Si el correo electrónico está registrado, recibirá instrucciones en breve.',
    'recover.forgot_password_text': '¿Olvidaste tu contraseña?',
    'recover.click_here': '¡Haga clic aquí!',
    // New keys for Modelos de Contrato
    'sidebar.templates': 'Modelos de Contrato',
    'templates.title': 'Biblioteca de Plantillas',
    'templates.subtitle': 'Seleccione una plantilla, complete los datos y descargue su contrato listo.',
    'templates.use_btn': 'Usar Plantilla',
    'templates.download_word': 'Descargar Word',
    'templates.download_pdf': 'Descargar PDF',
    'templates.fill_details': 'Rellenar Datos',
    'templates.preview': 'Vista Previa',
    'templates.back': 'Volver a la Lista',
    'templates.fill_title': 'Rellenar datos del contrato',
    'templates.generate_btn': 'Generar Contrato',
    'templates.send_sign': 'Enviar para Firmar',
    // New keys for Landing Page
    'landing.nav.pricing': 'Precios',
    'landing.nav.about': 'Sobre',
    'landing.nav.contact': 'Contacto',
    'landing.nav.login': 'Entrar',
    'landing.nav.platform': 'Acceder Plataforma',
    'landing.hero.title_start': 'Firme contratos',
    'landing.hero.title_end': 'en segundos',
    'landing.hero.subtitle': 'La plataforma más moderna para firmas digitales. Rápida, segura y con validez legal garantizada.',
    'landing.hero.start': 'Comenzar Gratis',
    'landing.hero.demo': 'Ver Demostración',
    'landing.features.title_start': 'Por qué elegir',
    'landing.features.subtitle': 'Una plataforma completa para gestionar sus documentos, firmas y comunicados en un solo lugar.',
    'landing.card.contract.title': 'Firma de Contratos',
    'landing.card.contract.desc': 'Envíe contratos para firmar con validez legal. Proceso simple, seguro y 100% digital.',
    'landing.card.multi.title': 'Múltiples Destinatarios',
    'landing.card.multi.desc': '¿Necesita varias firmas? Envíe a múltiples destinatarios por correo electrónico simultáneamente.',
    'landing.card.forms.title': 'Formularios Integrados',
    'landing.card.forms.desc': 'Cree formularios personalizados y envíe directamente por correo para recopilación de datos.',
    'landing.card.announce.title': 'Envío de Comunicados',
    'landing.card.announce.desc': 'Mantenga a todos informados. Envíe comunicados y avisos importantes por correo rápidamente.',
    'landing.card.simple.title': 'Sin Complicaciones',
    'landing.card.simple.desc': 'Hecho para facilitar su trabajo. Interfaz intuitiva y accesible para que se concentre en lo importante.',
    'landing.card.secure.title': 'Totalmente Seguro',
    'landing.card.secure.desc': 'Sus datos protegidos con cifrado de extremo a extremo. Seguridad y cumplimiento primero.',
    'landing.about.title': 'Sobre',
    'landing.about.desc1': 'VERYSING nació con el propósito de simplificar y proteger las relaciones comerciales en el entorno digital. Nuestra plataforma une la robustez de la seguridad criptográfica con una experiencia de uso intuitiva.',
    'landing.about.desc2': 'Transforme la burocracia en agilidade. Firme contratos en segundos, desde cualquier lugar del mundo.',
    'landing.about.stat1': 'Seguro',
    'landing.about.stat2': 'Disponible',
    'landing.about.badge': 'Firmado Digitalmente',
    'landing.demo.title': 'Vea',
    'landing.demo.title_end': 'en acción',
    'landing.demo.desc': 'Descubra cómo nuestra plataforma puede transformar su gestión de documentos y generar más ganancias.',
    'landing.demo.soon': 'Video de Demostración Pronto',
    'landing.pricing.title': 'Planes Flexibles',
    'landing.pricing.subtitle': 'Elija el plan ideal para su necesidad',
    'landing.pricing.free.title': 'Inicial',
    'landing.pricing.free.btn': 'Comenzar Gratis',
    'landing.pricing.free.feat1': '3 Documentos/mes',
    'landing.pricing.free.feat2': 'Firma Básica',
    'landing.pricing.free.feat3': 'Solo PDF',
    'landing.pricing.free.feat4': 'Soporte por Correo',
    'landing.pricing.pro.title': 'Profesional',
    'landing.pricing.pro.popular': 'MÁS POPULAR',
    'landing.pricing.pro.btn': 'Suscribir Pro',
    'landing.pricing.pro.feat1': 'Documentos Ilimitados',
    'landing.pricing.pro.feat2': 'Certificado Digital ICP-Brasil',
    'landing.pricing.pro.feat3': 'Gestión de Equipo',
    'landing.pricing.pro.feat4': 'Soporte Prioritario',
    'landing.pricing.ent.title': 'Empresarial',
    'landing.pricing.ent.btn': 'Suscribir Empresarial',
    'landing.pricing.ent.feat1': 'Todo del Pro',
    'landing.pricing.ent.feat2': 'API de Integración',
    'landing.pricing.ent.feat3': 'Dominio Personalizado',
    'landing.pricing.ent.feat4': 'Gerente de Cuenta Dedicado',
    'landing.footer': '© 2026 VERYSING. Todos los derechos reservados.',
    // Contact Page
    'contact.title': 'Contáctenos',
    'contact.subtitle': 'Complete el formulario a continuación y nos pondremos en contacto con usted lo antes posible.',
    'contact.form.title': 'Envíe un mensaje',
    'contact.form.name': 'Nombre',
    'contact.form.name_placeholder': 'Su nombre completo',
    'contact.form.email': 'Correo electrónico',
    'contact.form.email_placeholder': 'su@email.com',
    'contact.form.subject': 'Asunto',
    'contact.form.subject_placeholder': '¿Cómo podemos ayudar?',
    'contact.form.message': 'Mensaje',
    'contact.form.message_placeholder': 'Describa su duda o solicitud...',
    'contact.form.submit': 'Enviar Mensaje',
    'contact.info.title_start': 'Simplificando',
    'contact.info.title_middle': 'documentos',
    'contact.info.title_connector': ', conectando',
    'contact.info.title_end': 'personas',
    'contact.info.desc': 'Verysing nació para reducir la burocracia en las firmas. Más que una plataforma, somos sus socios en la agilidad de los negocios, garantizando seguridad y validez legal en cada acuerdo.',
    'contact.info.response_title': '¿Cómo recibiré la respuesta?',
    'contact.info.response_desc1': 'Nuestro equipo de soporte analizará su mensaje y enviará la respuesta directamente al correo electrónico informado en el formulario.',
    'contact.info.response_desc2': 'Por favor, verifique también su carpeta de spam o correo no deseado para asegurarse de no perder nuestro retorno.',
    'contact.alert.success': '¡Su mensaje ha sido enviado a contact.verysing@gmail.com! (Simulación)',

    'account.personal_info': 'Información Personal',
    'account.full_name': 'Nombre Completo',
    'account.phone': 'Teléfono',
    'account.job_title': 'Cargo',
    'account.save': 'Guardar Cambios',
    'account.security': 'Seguridad',
    'account.current_password': 'Contraseña Actual',
    'account.new_password': 'Nueva Contraseña',
    'account.update_password': 'Actualizar Contraseña',
    'account.plan_subscription': 'Plan y Suscripción',
    'account.plan_status': 'Activo',
    'account.plan_desc': 'Tienes 5 firmas mensuales gratuitas.',
    'account.upgrade': 'Mejorar Plan',
    // New keys for Forms
    'sidebar.forms': 'Formularios',
    'forms.title': 'Gestor de Formularios',
    'forms.create': 'Crear Nuevo Formulario',
    'forms.list': 'Mis Formularios',
    'forms.responses': 'Respuestas',
    'forms.send_title': 'Enviar Formulario',
    'forms.field_label': 'Título de la Pregunta',
    'forms.field_placeholder': 'Escriba su pregunta...',
    'forms.add_field': 'Añadir Campo',
    'forms.save': 'Guardar Formulario',
    'forms.send_to': 'Enviar a (Correo)',
    'forms.subject': 'Asunto',
    'forms.message': 'Mensaje',
    'forms.send_btn': 'Enviar por Correo',
    'forms.success_send': '¡Formulario enviado con éxito!',
    'forms.no_forms': 'Ningún formulario creado aún.',
    'forms.form_title': 'Título del Formulario',
    'forms.form_desc': 'Descripción',
    'forms.create_page_title': 'Crear Formulario',
    'forms.create_title': 'Nuevo Formulario',
    'forms.create_subtitle': 'Crea preguntas y envía para recolección de datos.',
    'forms.title_placeholder': 'Ej: Encuesta de Satisfacción',
    'forms.recipient_email_label': 'Enviar a (Correo del destinatario)',
    'forms.recipient_email_placeholder': 'destinatario@ejemplo.com',
    'forms.questions_title': 'Preguntas del Formulario',
    'forms.add_question': 'Añadir Pregunta',
    'forms.no_questions': 'Ninguna pregunta añadida.',
    'forms.start_building': 'Haz clic en "Añadir Pregunta" para comenzar a construir tu formulario.',
    'forms.question_number': 'Pregunta',
    'forms.delete': 'Eliminar',
    'forms.question_text_label': 'Texto de la Pregunta',
    'forms.question_text_placeholder': 'Escribe tu pregunta aquí...',
    'forms.response_type_label': 'Tipo de Respuesta Esperada',
    'forms.type_short': 'Texto Curto',
    'forms.type_long': 'Texto Largo',
    'forms.type_number': 'Número',
    'forms.type_email': 'Correo (Validación)',
    'forms.type_date': 'Fecha',
    'forms.type_select': 'Opción Múltiple (Selección)',
    'forms.required': 'Obligatorio',
    'forms.options_title': 'Opciones de Respuesta',
    'forms.option_placeholder': 'Opción',
    'forms.add_option': 'Añadir otra opción',
    'forms.submit_btn': 'Enviar Formulario',
    'forms.alert_fill': 'Por favor, rellena todos los campos obligatorios y añade al menos una pregunta.',
    'forms.alert_success': '¡Éxito! Un enlace para responder el formulario',
    'forms.alert_sent_to': 'fue enviado a',
    'forms.new_question_default': 'Nueva Pregunta',
    'forms.preview_btn': 'Previsualizar Correo',
    'forms.preview_title': 'Vista Previa del Correo',
    'forms.email_subject_prefix': 'Formulario: ',
    'forms.email_body_greeting': 'Hola,',
    'forms.email_body_invite': 'Has sido invitado a responder el formulario:',
    'forms.email_cta': 'Responder Formulario',
    'forms.modal_success_title': '¡Formulario Enviado con Éxito!',
    'forms.modal_success_message': 'La invitación ha sido enviada a',
    'forms.modal_close': 'Volver al Inicio',
    // Payment Page
    'payment.title': 'Pago',
    'payment.subtitle': 'Pago del plan',
    'payment.info_title': 'Información de pago',
    'payment.info_desc': 'Complete los detalles a continuación para finalizar la suscripción de su plan VerySing.',
    'payment.secure': 'Pago protegido con encriptación TLS',
    'payment.account': 'Cuenta:',
    'payment.select_plan': 'Seleccione el plan deseado',
    'payment.plan_free': 'Plan Gratuito',
    'payment.plan_pro': 'Plan Profesional',
    'payment.plan_ent': 'Plan Empresarial',
    'payment.desc_free': 'Plan gratuito ya activado, sin necesidad de pago.',
    'payment.desc_pro': 'Ideal para profesionales y pequeñas empresas con uso frecuente.',
    'payment.desc_ent': 'Para equipos y empresas que necesitan funciones avanzadas.',
    'payment.billing_annual_discount': 'Facturación anual con 10% de descuento.',
    'payment.free_plan_info': 'El Plan Gratuito ofrece acceso básico a la plataforma sin costos mensuales.',
    'payment.free_plan_confirm_info': 'Al confirmar, su plan se cambiará inmediatamente.',
    'payment.confirm_free': 'Confirmar Plan Gratuito',
    'payment.method_label': 'Método de pago',
    'payment.method_card': 'Tarjeta de Crédito',
    'payment.method_boleto': 'Boleto Bancario',
    'payment.method_pix': 'Pix',
    'payment.billing_cycle': 'Ciclo de facturación',
    'payment.billing_monthly': 'Mensual',
    'payment.billing_annual': 'Anual (Ahorre 10%)',
    'payment.card_number': 'Número de tarjeta',
    'payment.card_name': 'Nombre en la tarjeta',
    'payment.card_expiry': 'Validez (MM/AA)',
    'payment.card_cvv': 'Código de seguridad (CVV)',
    'payment.pay_now': 'Pagar Ahora',
    'payment.processing': 'Procesando...',
    'payment.generate_boleto': 'Generar Boleto',
    'payment.generate_pix': 'Generar Pix',
    'payment.boleto_title': 'Pago vía Boleto Bancario',
    'payment.boleto_desc': 'El boleto se generará en la siguiente pantalla. El plazo de compensación es de hasta 3 días hábiles.',
    'payment.pix_title': 'Pago vía Pix',
    'payment.pix_desc': 'El código Pix se generará en la siguiente pantalla. La aprobación es inmediata.',
    'payment.alert_fill': 'Complete todos los datos de la tarjeta para continuar.',
    'payment.success': '¡Pago realizado con éxito!',

  },
  fr: {
    'dashboard.title': 'Tableau de Bord',
    'account.title': 'Gérer le Compte',
    'sidebar.overview': 'Vue d\'ensemble',
    'sidebar.documents': 'Mes Documents',
    'sidebar.history': 'Historique',
    'sidebar.sign': 'Signer Document',
    'sidebar.send': 'Envoyer Enveloppe',
    'sidebar.account': 'Mon Compte',
    'sidebar.logout': 'Se Déconnecter',
    'welcome': 'Bon retour,',
    'welcome.subtitle': 'Voici le résumé de vos activités récentes.',
    'stats.signed': 'Contrats Signés',
    'stats.waiting': 'En Attente de Signature',
    'stats.total': 'Total des Documents',
    'activity.title': 'Activité Récente',
    'table.document': 'Document',
    'table.recipient': 'Destinataire',
    'table.date': 'Date',
    'table.status': 'Statut',
    'status.completed': 'Terminé',
    'status.waiting': 'En Attente',
    'menu.account': 'Mon Compte',
    'menu.language': 'Langue',
    'user.plan': 'Plan Gratuit',
    'btn.create_account': 'S\'inscrire',
    'btn.login': 'Connexion',
    'nav.features': 'Fonctionnalités',
    'nav.pricing': 'Tarifs',
    'nav.about': 'À Propos',
    'landing.nav.home': 'Accueil',
    'landing.nav.menu': 'Menu',
    'landing.nav.features': 'Fonctionnalités',
    'landing.nav.pricing': 'Tarifs',
    'landing.nav.about': 'À propos',
    'landing.nav.contact': 'Contact',
    'landing.nav.login': 'Connexion',
    'landing.nav.platform': 'Accéder à la plateforme',
    'landing.hero.title_start': 'Signez des contrats',
    'landing.hero.title_end': 'en quelques secondes',
    'landing.hero.subtitle': 'La plateforme de signature numérique la plus moderne. Rapide, sécurisée et juridiquement contraignante.',
    'landing.hero.start': 'Commencer Gratuitement',
    'landing.hero.demo': 'Voir la Démo',
    'landing.features.title_start': 'Pourquoi choisir',
    'landing.features.subtitle': 'Une plateforme complète pour gérer vos documents, signatures et communiqués en un seul endroit.',
    'landing.card.contract.title': 'Signature de Contrats',
    'landing.card.contract.desc': 'Envoyez des contrats pour signature avec validité juridique. Processus simple, sécurisé et 100% numérique.',
    'landing.card.multi.title': 'Multi-Destinataires',
    'landing.card.multi.desc': 'Besoin de plusieurs signatures ? Envoyez simultanément à plusieurs destinataires par e-mail.',
    'landing.card.forms.title': 'Formulaires Intégrés',
    'landing.card.forms.desc': 'Créez des formulaires personnalisés et envoyez-les directement par e-mail pour la collecte de données.',
    'landing.card.announce.title': 'Envoi de Communiqués',
    'landing.card.announce.desc': 'Tenez tout le monde informé. Envoyez rapidement des annonces et des avis importants par e-mail.',
    'landing.card.simple.title': 'Sans Complication',
    'landing.card.simple.desc': 'Conçu pour faciliter votre travail. Interface intuitive et accessible pour vous concentrer sur l\'essentiel.',
    'landing.card.secure.title': 'Totalmente Sécurisé',
    'landing.card.secure.desc': 'Vos données protégées par un cryptage de bout en bout. Sécurité et conformité avant tout.',
    'landing.about.title': 'À propos de',
    'landing.about.desc1': 'VERYSING est né dans le but de simplifier et de protéger les relations commerciales dans l\'environnement numérique. Notre plateforme allie une sécurité cryptographique robuste à une expérience utilisateur intuitive et fluide.',
    'landing.about.desc2': 'Transformez la bureaucratie en agilité. Signez des contrats en quelques secondes, de n\'importe où dans le monde.',
    'landing.about.stat1': 'Sécurisé',
    'landing.about.stat2': 'Disponible',
    'landing.about.badge': 'Signé Numériquement',
    'landing.demo.title': 'Voir',
    'landing.demo.title_end': 'en action',
    'landing.demo.desc': 'Découvrez comment notre plateforme peut transformer votre gestion documentaire et générer plus de profits pour votre entreprise.',
    'landing.demo.soon': 'Vidéo de Démo Bientôt Disponible',
    'landing.pricing.title': 'Plans Flexibles',
    'landing.pricing.subtitle': 'Choisissez le plan idéal pour vos besoins',
    'landing.pricing.free.title': 'Débutant',
    'landing.pricing.free.btn': 'Commencer Gratuitement',
    'landing.pricing.free.feat1': '3 Documents/mois',
    'landing.pricing.free.feat2': 'Signature De Base',
    'landing.pricing.free.feat3': 'PDF Uniquement',
    'landing.pricing.free.feat4': 'Support par E-mail',
    'landing.pricing.pro.title': 'Professionnel',
    'landing.pricing.pro.popular': 'LE PLUS POPULAIRE',
    'landing.pricing.pro.btn': 'S\'abonner Pro',
    'landing.pricing.pro.feat1': 'Documents Illimités',
    'landing.pricing.pro.feat2': 'Certificat Numérique ICP-Brasil',
    'landing.pricing.pro.feat3': 'Gestion d\'Équipe',
    'landing.pricing.pro.feat4': 'Support Prioritaire',
    'landing.pricing.ent.title': 'Entreprise',
    'landing.pricing.ent.btn': 'Souscrire Entreprise',
    'landing.pricing.ent.feat1': 'Tout du Pro',
    'landing.pricing.ent.feat2': 'API d\'Intégration',
    'landing.pricing.ent.feat3': 'Domaine Personnalisé',
    'landing.pricing.ent.feat4': 'Gestionnaire de Compte Dédié',
    'landing.footer': '© 2026 VERYSING. Tous droits réservés.',
    // Contact Page
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Remplissez le formulaire ci-dessous et nous vous contacterons dès que possible.',
    'contact.form.title': 'Envoyez un message',
    'contact.form.name': 'Nom',
    'contact.form.name_placeholder': 'Votre nom complet',
    'contact.form.email': 'E-mail',
    'contact.form.email_placeholder': 'votre@email.com',
    'contact.form.subject': 'Sujet',
    'contact.form.subject_placeholder': 'Comment pouvons-nous aider ?',
    'contact.form.message': 'Message',
    'contact.form.message_placeholder': 'Décrivez votre question ou demande...',
    'contact.form.submit': 'Envoyer le Message',
    'contact.info.title_start': 'Simplifier les',
    'contact.info.title_middle': 'documents',
    'contact.info.title_connector': ', connecter les',
    'contact.info.title_end': 'gens',
    'contact.info.desc': 'Verysing est né pour réduire la bureaucratie des signatures. Plus qu\'une plateforme, nous sommes vos partenaires pour l\'agilité commerciale, garantissant sécurité et validité juridique dans chaque accord.',
    'contact.info.response_title': 'Comment recevrai-je la réponse ?',
    'contact.info.response_desc1': 'Notre équipe de support analysera votre message et enverra la réponse directement à l\'e-mail fourni dans le formulaire.',
    'contact.info.response_desc2': 'Veuillez également vérifier votre dossier spam ou courrier indésirable pour vous assurer de ne pas manquer notre retour.',
    'contact.alert.success': 'Votre message a été envoyé à contact.verysing@gmail.com ! (Simulation)',
    // New keys for EnviarDocumento
    'documents.title': 'Mes Documents',
    'documents.new_folder': 'Nouveau Dossier',
    'documents.upload': 'Nouveau Document',
    'documents.search': 'Rechercher des documents...',
    'documents.empty': 'Aucun document trouvé dans ce dossier.',
    'documents.name': 'Nom',
    'documents.date': 'Date',
    'documents.size': 'Taille',
    'documents.category': 'Catégorie',
    'documents.folder_name': 'Nom du Dossier',
    'documents.create': 'Créer',
    'documents.cancel': 'Annuler',
    'documents.all': 'Tous les Documents',
    'documents.uncategorized': 'Sans Catégorie',
    'documents.delete': 'Supprimer',
    'documents.rename': 'Renommer',
    'documents.move': 'Déplacer',

    'send.title': 'Envoyer Enveloppe',
    'send.add_docs': 'Ajouter des Documents',
    'send.select_doc': 'Sélectionnez le document à envoyer (PDF, DOCX)',
    'send.click_search': 'Cliquez pour parcourir votre ordinateur',
    'send.file_selected': 'Fichier sélectionné:',
    'send.recipients': 'Destinataires',
    'send.self_sign': 'Je dois aussi signer le document',
    'send.your_data': 'Vos Détails (Vous)',
    'send.your_name': 'Votre Nom',
    'send.your_email': 'Votre E-mail',
    'send.recipient': 'Destinataire',
    'send.name': 'Nom',
    'send.email': 'E-mail',
    'send.role': 'Rôle',
    'send.role.signer': 'SIGNATAIRE',
    'send.role.witness': 'TÉMOIN',
    'send.role.approver': 'APPROBATEUR',
    'send.add_recipient': 'Ajouter un autre destinataire',
    'send.message_all': 'Message à tous',
    'send.subject': 'Sujet de l\'E-mail',
    'send.message': 'Message',
    'send.submit': 'Envoyer Enveloppe',
    'send.deadline_title': 'Délai de Signature',
    'send.deadline_label': 'Date Limite de Signature',
    'send.auto_reminder': 'Envoyer un e-mail automatique le dernier jour',
    'send.description': 'Remplissez les champs ci-dessous pour configurer l\'envoi du document.',
    // New keys for Home (Assinar)
    'sign.title': 'Signataire de Contrat Sécurisé',
    'sign.select_doc': 'Sélectionnez le document à signer (PDF, DOCX)',
    'sign.data_title': 'Données de Signature',
    'sign.contractor': 'Contractant',
    'sign.contracted': 'Contracté',
    'sign.type': 'Taper',
    'sign.draw': 'Dessiner',
    // New keys for EnviarComunicado
    'sidebar.announce': 'Envoyer Communiqué',
    'announce.title': 'Envoyer Communiqué',
    'announce.subtitle': 'Envoyez des e-mails informatifs avec votre marque.',
    'announce.logo_label': 'Logo de l\'En-tête',
    'announce.logo_placeholder': 'Cliquez pour télécharger le logo',
    'announce.subject_label': 'Sujet de l\'E-mail',
    'announce.message_label': 'Corps du Message',
    'announce.recipients_label': 'Destinataires (séparés par des virgules)',
    'announce.recipients_placeholder': 'exemple@email.com, autre@email.com',
    'announce.preview_btn': 'Prévisualiser',
    'announce.send_btn': 'Envoyer Communiqué',
    'announce.preview_title': 'Prévisualisation de l\'E-mail',
    'announce.confirm_send': 'Confirmer l\'Envoi',
    'announce.edit': 'Retour et Éditer',
    'announce.success': 'Communiqué envoyé avec succès !',
    'announce.logo_help': 'Recommandé : Image PNG ou JPG transparente.',
    // New keys for Password Recovery
    'recover.title': 'Réinitialiser le mot de passe',
    'recover.subtitle': 'Saisissez votre e-mail pour recevoir les instructions de réinitialisation.',
    'recover.email_label': 'Votre e-mail',
    'recover.email_placeholder': 'Saisissez votre e-mail enregistré',
    'recover.submit_btn': 'Envoyer les instructions',
    'recover.back_login': 'Retour à la connexion',
    'recover.success_message': 'Si cet e-mail est enregistré, vous recevrez bientôt les instructions.',
    'recover.forgot_password_text': 'Mot de passe oublié ?',
    'recover.click_here': 'Cliquez ici !',
    // New keys for Modelos de Contrato
    'sidebar.templates': 'Modèles de Contrat',
    'templates.title': 'Bibliothèque de Modèles',
    'templates.subtitle': 'Sélectionnez un modèle, remplissez les détails et téléchargez votre contrat prêt.',
    'templates.use_btn': 'Utiliser le Modèle',
    'templates.download_word': 'Télécharger Word',
    'templates.download_pdf': 'Télécharger PDF',
    'templates.fill_details': 'Remplir les Détails',
    'templates.preview': 'Aperçu',
    'templates.back': 'Retour à la Liste',
    'templates.fill_title': 'Remplir les détails du contrat',
    'templates.generate_btn': 'Générer Contrat',
    'templates.send_sign': 'Envoyer pour Signature',
    'sign.clear': 'Effacer',
    'sign.full_name': 'Nom Complet',
    'sign.submit': 'Signer Document',
    // New keys for Dashboard (Account)
    'account.personal_info': 'Informations Personnelles',
    'account.full_name': 'Nom Complet',
    'account.phone': 'Téléphone',
    'account.job_title': 'Poste',
    'account.save': 'Sauvegarder',
    'account.security': 'Sécurité',
    'account.current_password': 'Mot de passe actuel',
    'account.new_password': 'Nouveau mot de passe',
    'account.update_password': 'Mettre à jour',
    'account.plan_subscription': 'Plan et Abonnement',
    'account.plan_status': 'Actif',
    'account.plan_desc': 'Vous avez 5 signatures mensuelles gratuites.',
    'account.upgrade': 'Mettre à niveau',
    // New keys for Forms
    'sidebar.forms': 'Formulaires',
    'forms.create_page_title': 'Créer Formulaire',
    'forms.create_title': 'Nouveau Formulaire',
    'forms.create_subtitle': 'Créez des questions et envoyez pour la collecte de données.',
    'forms.title_placeholder': 'Ex: Enquête de Satisfaction',
    'forms.form_title': 'Titre du Formulaire',
    'forms.recipient_email_label': 'Envoyer à (E-mail du destinataire)',
    'forms.recipient_email_placeholder': 'destinataire@exemple.com',
    'forms.questions_title': 'Questions du Formulaire',
    'forms.add_question': 'Ajouter Question',
    'forms.no_questions': 'Aucune question ajoutée.',
    'forms.start_building': 'Cliquez sur "Ajouter Question" pour commencer à construire votre formulaire.',
    'forms.question_number': 'Question',
    'forms.delete': 'Supprimer',
    'forms.question_text_label': 'Texte de la Question',
    'forms.question_text_placeholder': 'Tapez votre question ici...',
    'forms.response_type_label': 'Type de Réponse Attendue',
    'forms.type_short': 'Texte Court',
    'forms.type_long': 'Texte Long',
    'forms.type_number': 'Nombre',
    'forms.type_email': 'E-mail (Validation)',
    'forms.type_date': 'Date',
    'forms.type_select': 'Choix Multiple (Sélection)',
    'forms.required': 'Obligatoire',
    'forms.options_title': 'Options de Réponse',
    'forms.option_placeholder': 'Option',
    'forms.add_option': 'Ajouter une autre option',
    'forms.submit_btn': 'Envoyer Formulaire',
    'forms.alert_fill': 'Veuillez remplir tous les champs obligatoires et ajouter au moins une question.',
    'forms.alert_success': 'Succès ! Un lien pour répondre au formulaire',
    'forms.alert_sent_to': 'a été envoyé à',
    'forms.new_question_default': 'Nouvelle Question',
    'forms.preview_btn': 'Prévisualiser l\'E-mail',
    'forms.preview_title': 'Aperçu de l\'E-mail',
    'forms.email_subject_prefix': 'Formulaire : ',
    'forms.email_body_greeting': 'Bonjour,',
    'forms.email_body_invite': 'Vous avez été invité à répondre au formulaire :',
    'forms.email_cta': 'Répondre au Formulaire',
    'forms.modal_success_title': 'Formulaire Envoyé avec Succès !',
    'forms.modal_success_message': 'L\'invitation a été envoyée à',
    'forms.modal_close': 'Retour au Tableau de Bord',
    // New keys for History
    'history.title': 'Historique des Communications',
    'history.subtitle': 'Suivez les performances des annonces envoyées et les taux d\'ouverture.',
    'history.subject': 'Sujet',
    'history.sent_at': 'Envoyé à',
    'history.recipients': 'Destinataires',
    'history.opens': 'Ouvertures',
    'history.open_rate': 'Taux d\'ouverture',
    'history.status_opened': 'Ouvert',
    'history.status_not_opened': 'Non ouvert',
    'history.rate': 'Taux',
    'history.actions': 'Actions',
    'history.view_recipients': 'Voir destinataires',
    'history.no_announcements': 'Aucune annonce envoyée pour le moment.',
    'history.recipients_opens_title': 'Destinataires et Ouvertures',
    'history.recipients_opens_subtitle': 'Voir qui a reçu et ouvert l\'annonce sélectionnée.',
    'history.select_instruction': 'Sélectionnez une annonce dans la liste pour voir les détails.',
    'history.name': 'Nom',
    'history.email': 'E-mail',
    'history.status': 'Statut',
    'history.first_open': 'Première ouverture',
    'history.no_recipients': 'Aucun destinataire trouvé pour cette annonce.',
    'history.status_opened_badge': 'Ouvert',
    'history.status_not_opened_badge': 'Non ouvert',
    // Payment Page
    'payment.title': 'Paiement',
    'payment.subtitle': 'Paiement du forfait',
    'payment.info_title': 'Informations de paiement',
    'payment.info_desc': 'Remplissez les détails ci-dessous pour finaliser votre abonnement au forfait VerySing.',
    'payment.secure': 'Paiement protégé par cryptage TLS',
    'payment.account': 'Compte :',
    'payment.select_plan': 'Sélectionnez le forfait souhaité',
    'payment.plan_free': 'Forfait Gratuit',
    'payment.plan_pro': 'Forfait Professionnel',
    'payment.plan_ent': 'Forfait Entreprise',
    'payment.desc_free': 'Forfait gratuit déjà activé, aucun paiement requis.',
    'payment.desc_pro': 'Idéal pour les professionnels et les petites entreprises à usage fréquent.',
    'payment.desc_ent': 'Pour les équipes et les entreprises ayant besoin de fonctionnalités avancées.',
    'payment.billing_annual_discount': 'Facturation annuelle avec 10 % de réduction.',
    'payment.free_plan_info': 'Le forfait gratuit offre un accès de base à la plateforme sans frais mensuels.',
    'payment.free_plan_confirm_info': 'Dès confirmation, votre forfait sera modifié immédiatement.',
    'payment.confirm_free': 'Confirmer le Forfait Gratuit',
    'payment.method_label': 'Mode de paiement',
    'payment.method_card': 'Carte de Crédit',
    'payment.method_boleto': 'Boleto Bancaire',
    'payment.method_pix': 'Pix',
    'payment.billing_cycle': 'Cycle de facturation',
    'payment.billing_monthly': 'Mensuel',
    'payment.billing_annual': 'Annuel (Économisez 10 %)',
    'payment.card_number': 'Numéro de carte',
    'payment.card_name': 'Nom sur la carte',
    'payment.card_expiry': 'Validité (MM/AA)',
    'payment.card_cvv': 'Code de sécurité (CVV)',
    'payment.pay_now': 'Payer Maintenant',
    'payment.processing': 'Traitement...',
    'payment.generate_boleto': 'Générer Boleto',
    'payment.generate_pix': 'Générer Pix',
    'payment.boleto_title': 'Paiement par Boleto Bancaire',
    'payment.boleto_desc': 'Le boleto sera généré sur l\'écran suivant. Le délai de compensation est de 3 jours ouvrables.',
    'payment.pix_title': 'Paiement par Pix',
    'payment.pix_desc': 'Le code Pix sera généré sur l\'écran suivant. L\'approbation est immédiate.',
    'payment.alert_fill': 'Remplissez toutes les coordonnées de la carte pour continuer.',
    'payment.success': 'Paiement réussi !',

  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};